### PR TITLE
Logo-Header

### PR DESCRIPTION
**Pull request by JatinBhargava**
See it's all right.
Please Merge coz it's my PR.
Still, if you need any modification let me know.

### CODE REVIEW

**Comment by devgossips** [comment]
But I want a different thing !!! 
IMG_20211031_082432
Fix this one .

**Comment by JatinBhargava** [comment]
> But I want a different thing !!! IMG_20211031_082432 Fix this one .

For that you have to merge my pr then only you can see the change or inspect on  
Inspect: https://vercel.com/devgossips/bio/2w9QFoAT4LspL9DKLurPEriK3XRn

**Comment by devgossips** [comment]
are you wanting this for hacktoberfest ?

**Comment by JatinBhargava** [comment]
Yes

**Comment by devgossips** [comment]
.

**Pull request closed without merging**
